# -*- coding: utf-8 -*-
"""facial-deblur-models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuSJqmVRoQODA6UNj6XIX5I145h3bcl8
"""

import torch
import torch.nn as nn

from PIL import Image
import os
import torchvision.transforms as T
import torch.optim as optim

import json
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import torch.nn as nn

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
base_drive_path = '/content/gdrive/MyDrive/'

class DilatedCNN(nn.Module):
    def __init__(self):
        super(DilatedCNN, self).__init__()

        self.network = nn.Sequential(
            # First layer
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.ReLU(),

            # Second layer
            nn.Conv2d(32, 32, kernel_size=3, padding=2, dilation=2),
            nn.ReLU(),

            # Third layer
            nn.Conv2d(32, 3, kernel_size=3, padding=1),
        )

    def forward(self, x):
        return self.network(x)

class DeblurCNN(nn.Module):
    def __init__(self):
        super(DeblurCNN, self).__init__()

        self.encoder = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=5, padding=2),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=5, padding=2),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=5, padding=2),
            nn.ReLU(),
        )

        self.decoder = nn.Sequential(
            nn.Conv2d(128, 64, kernel_size=5, padding=2),
            nn.ReLU(),
            nn.Conv2d(64, 32, kernel_size=5, padding=2),
            nn.ReLU(),
            nn.Conv2d(32, 3, kernel_size=5, padding=2),
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return decoded

class ShallowCNN(nn.Module):
    def __init__(self):
        super(ShallowCNN, self).__init__()
        #single-pass convolution block
        self.network = nn.Sequential(
            # Input
            nn.Conv2d(3, 32, kernel_size=5, padding=2),
            nn.ReLU(),
            # Output
            nn.Conv2d(32, 3, kernel_size=5, padding=2),
        )

    def forward(self, x):
        return self.network(x)

class ShallowResidualNet(nn.Module):
    def __init__(self):
        super(ShallowResidualNet, self).__init__()

        self.res_block = nn.Sequential(
            #Layer 1
            nn.Conv2d(3, 32, kernel_size=5, padding=2),
            nn.ReLU(),
            #Layer 2
            nn.Conv2d(32, 3, kernel_size=5, padding=2),
        )

    def forward(self, x):
        residual = self.res_block(x)
        output = x + residual

        return output

transform = T.Compose([
            T.Resize((256, 256)),
            T.ToTensor(),
        ])

import torchvision.transforms.functional as TF

model = DilatedCNN().to(device)

criterion = nn.L1Loss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

num_epochs = 10

for epoch in range(num_epochs):
    for k in range(1,2):
        print(f'a thousand')
        if(k < 10):
            first = '0' + str(k)
        else:
            first = str(k)
        data_dir = os.path.join(base_drive_path, 'ffhq-dataset/images1024x1024/' + first + '000')
        print("starting")
        for i in range(0, 1000):
            if(i%100 == 0):
                print(i)

            if(i < 10):
                image_file = first + '00' + str(i) + '.png'
            elif(i < 100):
                image_file = first + '0' + str(i) + '.png'
            else:
                image_file = first + str(i) + '.png'

            sharp_path = os.path.join(data_dir, image_file)
            blur_path = "/content/gdrive/MyDrive/blurred/blurred_" + image_file

            blur = Image.open(blur_path).convert("RGB")
            sharp = Image.open(sharp_path).convert("RGB")

            sharp = transform(sharp)
            blurred = transform(blur)

            blurred = blurred.to(device)
            sharp = sharp.to(device)

            blurred_batch = blurred.unsqueeze(0)
            sharp_batch = sharp.unsqueeze(0)

            output = model(blurred_batch)
            loss = criterion(output, sharp_batch)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    print(f"Epoch [{epoch+1}/{num_epochs}] Loss: {loss.item():.4f}")

torch.save(model.state_dict(), "/content/gdrive/MyDrive/deblur_dilated_cnn.pth")
print("Model saved!")

model = DilatedCNN().to(device)
model.load_state_dict(torch.load("/content/gdrive/MyDrive/deblur_dilated_cnn.pth", map_location=device))
model.eval()

# Transform
transform = T.Compose([
    T.Resize((256, 256)),
    T.ToTensor(),
])

# Load blurred image
img = Image.open("/content/gdrive/MyDrive/blurred/blurred_01999.png").convert("RGB")
inp = transform(img).unsqueeze(0).to(device)

# Inference
with torch.no_grad():
    output = model(inp)

# Postprocess
output = torch.clamp(output.squeeze(0), 0, 1)
result = TF.to_pil_image(output.cpu())

# Save + show
result.save("deblurred_result2.jpg")
result.show()

"""#label deblurred emotion"""

# Load model directly
from transformers import AutoImageProcessor, AutoModelForImageClassification

processor = AutoImageProcessor.from_pretrained("dima806/facial_emotions_image_detection")
model = AutoModelForImageClassification.from_pretrained("dima806/facial_emotions_image_detection")

os.environ['HF_TOKEN'] = 'token'

from huggingface_hub import InferenceClient

client = InferenceClient(
    provider="auto",
    api_key=os.environ["HF_TOKEN"],
)

emotions = {}

# Load model
model = ShallowResidualNet().to(device)
model.load_state_dict(torch.load("/content/gdrive/MyDrive/deblur_shallow_residual.pth", map_location=device))
model.eval()

for k in range(1,2):
    print(f'a thousand')
    if(k < 10):
        first = '0' + str(k)
    else:
        first = str(k)
    data_dir = os.path.join(base_drive_path, 'ffhq-dataset/images1024x1024/' + first + '000')
    print("starting")
    for i in range(0, 1000):
        if(i < 10):
            image_file = first + '00' + str(i) + '.png'
        elif(i < 100):
            image_file = first + '0' + str(i) + '.png'
        else:
            image_file = first + str(i) + '.png'
        sharp_path = os.path.join(data_dir, image_file)
        blur_path = "/content/gdrive/MyDrive/blurred/blurred_" + image_file


        # Load blurred image
        img = Image.open(blur_path).convert("RGB")
        inp = transform(img).unsqueeze(0).to(device)

        # Inference
        with torch.no_grad():
            output = model(inp)

        # Postprocess
        output = torch.clamp(output.squeeze(0), 0, 1)
        result = TF.to_pil_image(output.cpu())

        # Convert PIL Image to bytes
        result.save("/tmp/deblurred.png")

        output = client.image_classification(
            "/tmp/deblurred.png",
            model="dima806/facial_emotions_image_detection"
        )
        emotions[image_file] = output

"""#Creates file for deblurred emotion data"""

emotions

import json
output_filename = "shallow_resnet_emotions_data.json"

# Load existing data (list of dicts)
try:
    with open(output_filename, 'r') as f:
        if os.stat(output_filename).st_size > 0:
            data = json.load(f)
            if isinstance(data, dict):
                data = [data]
except FileNotFoundError:
    print("error")
    data = []

print(emotions)
# Append new result
data.append(emotions)

# Write updated list back to JSON
with open(base_drive_path + output_filename, 'w') as f:
    json.dump(data, f, indent=4)

print("Saved successfully!")